### ISSUE TITLE
SBT 1.0.0 release

### ISSUE THREAD

**Issue by MateuszKubuszok** [blstream/sbt-search-maven-plugin#3]
Or SBT 1.0.2 ;)

@lukeindykiewicz ?

**Comment by lukeindykiewicz** [comment]
I don't think anybody maintains this plugin anymore. I would have to fork it, as I don't have access right to this repo anymore.
hello?

@MateuszKubuszok keep fingers crossed for me having some spare time

**Comment by krzemin** [comment]
> I would have to fork it

go for it 👍

**Comment by lukeindykiewicz** [comment]
sbt 1.1.0 supported with sbt-search-maven-plugin 0.2.0
Development moved to: https://github.com/lukeindykiewicz/sbt-search-maven-plugin
